export const types = {
    ADD_TO_WATCH_LATER: 'ADD_TO_WATCH_LATER',
    REMOVE_FROM_WATCH_LATER: 'REMOVE_FROM_WATCH_LATER',
    ADD_COMMENT: 'ADD_COMMENT',
    EDIT_COMMENT: 'EDIT_COMMENT',
    REMOVE_COMMENT: 'REMOVE_COMMENT',
    ADD_TO_PLAYLIST: 'ADD_TO_PLAYLIST',
    ADD_TO_EXISTING_PLAYLIST: 'ADD_TO_EXISTING_PLAYLIST',
    REMOVE_FROM_PLAYLIST: 'REMOVE_FROM_PLAYLIST'
}